baseURL = "https://sagami.one/" #
languageCode = 'ja'
title = 'さがみ産業医事務所'  # さがみ産業医事務所 | 東京
enableEmoji = true
#theme = "hugo-tranquilpeak-theme"
defaultContentLanguage = "ja"
hasCJKLanguage = true
summaryLength = 0
paginate = 6

[pagination]
  disableAliases = true
  pagerSize = 6
  path = 'page'


[permalinks]
  post = "/:year/:month/:day/"

[params]
  sidebarBehavior = 2
  thumbnailImage = true
  dateFormat = "2006-01-02"
  thumbnailImagePosition = "left"
  autoThumbnailImage = true
#  coverImage = "https://images.unsplash.com/photo-1604928141064-207cea6f571f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8?q=75&w=1280&auto=format&fit=crop"
  imageGallery = true
  hierarchicalCategories = true
  syntaxHighlighter = 'highlight.js'
	keywords = ['産業医', '東京', '労働衛生コンサルタント', 'メンタル', 'ストレスチェック', '集団分析']
  favicon = "img/favicon.png"
  
  googletagID = 'G-0R60H25J3D'

  [[params.customCSS]]
        href = "css/mystyle_v4.css"
        
  [params.header.rightLink]
    class = ""
    icon = ""
    url = "#about" 

  [params.author]
  name = "さがみ産業医事務所"
  email = "office@sagami.one"

[author]
  slogan = "働くすべての人が健康のスキル・知識を身に着けて活躍する社会の実現"
  location = "Tokyo, Japan"
  title = "Good Condition Doctor"
#  gravatarEmail = "office@sagami.one"
  picture= "img/symbol_mark_small.svg"

[[menu.main]]
  weight = 1
  identifier = "home"
  name = "ホーム"
  pre = "<span class=\"sidebar-button-icon home-icon\" aria-hidden=\"true\"></span>"
  url = "index.html"
  
[[menu.main]]
  weight = 2
  identifier = "tadano"
  name = "当社の強み"
  pre = "<span class=\"sidebar-button-icon strength-icon\" aria-hidden=\"true\"></span>"
  url = "posts/tadano/"
  
[[menu.main]]
  weight = 3
  identifier = "profile"
  name = "プロフィール"
  pre = "<span class=\"sidebar-button-icon profile-icon\" aria-hidden=\"true\"></span>"
  url = "posts/profile/"

[[menu.main]]
  weight = 4
  identifier = "youtube"
  name = "動画制作・企画・監修"
  pre = "<span class=\"sidebar-button-icon video-icon\" aria-hidden=\"true\"></span>"
  url = "posts/youtube/"
  
[[menu.main]]
  weight = 5
  identifier = "company"
  name = "会社概要"
  pre = "<span class=\"sidebar-button-icon company-icon\" aria-hidden=\"true\"></span>"
  url = "posts/company/"

[[menu.main]]
  weight = 6
  identifier = "contact"
  name = "お問合わせ"
  pre = "<span class=\"sidebar-button-icon contact-icon\" aria-hidden=\"true\"></span>"
  url = "posts/contact/"
  
[[menu.links]]
  weight = 7
  identifier = "lecture"
  name = "研修・講演"
  pre = "<span class=\"sidebar-button-icon lecture-icon\" aria-hidden=\"true\"></span>"
  url = "posts/lecture/"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
  unsafe = true

